### ISSUE TITLE
Child pages of a page with a URI that matches a custom post type slug

### ISSUE THREAD

**Issue by dominicwhittle** [jchristopher/hierarchy#14]
Question — not bug

I have a page Science (/science) and custom posts for Science Projects ('slug' => 'science') and Hierarchy does it's thing nicely. Problem is that my client has added a child page — Conservation... (/science/conservation) — which 404s. 

The obvious answer is "don't make pages there". But do you have a suggestion or approach for dealing with this slug conflict? 

(Just listened to your talk with Pippin and Brad, btw)

![screen shot 2015-07-15 at 3 16 26 pm](https://cloud.githubusercontent.com/assets/611704/8691387/34cc4f66-2b05-11e5-9d27-7d0466ead6d2.jpg)

**Comment by jchristopher** [comment]
Hi @dominicwhittle I'm quite sure that the CPT will take over that slug and you can't mix/match Pages within there. That's actually a WordPress thing (and I'll double check) but I don't think it's possible.

**Comment by dominicwhittle** [comment]
@jchristopher You're correct. I just wondered if you had an approach for dealing with this kind of thing. I figured you would have come across it before. All good. Thanks!
